### ISSUE TITLE
Add support for rendering mathematical notation

### ISSUE THREAD

**Issue by begleynk** [Doctave/doctave#14]
Like mdbook and others, we should add support for mathematical notation.

[MathJax](https://www.mathjax.org/) seems like it could be a good option. It could be integrated similarly to how we do with MermaidJS - bundle the minified JS in the binary and serve it.

Discussion found here: https://www.reddit.com/r/rust/comments/qpeblj/comment/hjuxq5d/

**Comment by begleynk** [comment]
One issue with MathJax seems to be that it requires a polyfill library to also be loaded for browser compatibility. This is required even for IE 11 support. [Details here](https://docs.mathjax.org/en/latest/output/browser.html).

Perhaps [Katex](https://github.com/KaTeX/KaTeX/) could be a more lightweight option? It's around ~250kb minified and is self contained.

**Comment by pdunne** [comment]
good point, I forgot that my quick test was with Katex (it almost displayed correctly)
