### ISSUE TITLE
Code in headings breaks `On this page` text

### ISSUE THREAD

**Issue by oeb25** [Doctave/doctave#15]
Hi there, just stumbled over this issue. If I have inline code in a heading, all succeeding text will be truncated.

To reproduce create a file with the contents:
```md
# Foo `bar` baz
```
The right `On this page` navigation will have a single item of `Foo `, missing the rest of the title.

**Comment by begleynk** [comment]
Thanks for reporting this. Let me investigate a bit. I have a suspicion I know what the issue is here.

**Comment by begleynk** [comment]
Are you still seeing this issue? I just tried to reproduce what you described but I'm seeing what I think is the expected output:

![Screenshot 2021-12-28 at 11-44-32 test](https://user-images.githubusercontent.com/1065208/147553073-a46d28d0-8192-4ce4-bd59-c7b7049d2356.png)

**Comment by begleynk** [comment]
Oh - my mistake. You're talking about the right side navigation. I'm seeing the issue too.

**Comment by oeb25** [comment]
Thanks a lot, looks good!
