### ISSUE TITLE
Use updated mermaid.js

### ISSUE THREAD

**Issue by vikesh-raj** [Doctave/doctave#17]
Doctave is currently using mermaid.js with version 8.8.0. The latest release of mermaid.js is 8.13.3.
I am currently observing differences in mermaid live editor and the doctave rendered pages because of the version change.

In general, is it possible to keep these javascript libraries updated via a build script ?

**Comment by begleynk** [comment]
Thanks for reporting this. The Mermaid JS version is admittedly a bit old so it could be updated.

Would you be able to post screenshots of the differences you see between Doctave and the live editor?

I'd prefer however to keep updating dependencies manually. I wouldn't want any breaking changes made downstream to be pulled into a Doctave release without careful consideration.

**Comment by vikesh-raj** [comment]
Mermaid.js code

`
flowchart TD
   classDef yellow fill:yellow
   label[Label]
   class label yellow
`

[Preview](https://imgur.com/a/RuLgNYq)

**Comment by begleynk** [comment]
Ah I see some of the newer theme features are not in the Doctave bundled version. Gotcha. We'll bump the Mermaid JS version in the next release.

Just to clarify - how did you generate the page with the yellow label? Did you override the Mermaid JS version somehow?

**Comment by vikesh-raj** [comment]
I rebuilt the doctave binary with latest mermaid.js placed in src/assets folder.
