### ISSUE TITLE
how to install for windows??

### ISSUE THREAD

**Issue by zumdar** [Doctave/doctave#3]
this looks like a great tool, but I really can't figure out how to get it install it!

Ive downloaded the .exe file. ran it, ran it via my bash cli, ran it via powershell, downloaded rust and cargo, tried to install that way but then i got an error saying i needed some visual studio tools...

There must be a simple step that I dont know about here?

**Comment by begleynk** [comment]
Thanks for the kind words! There are 2 ways to install Doctave on Windows: download the precompiled binary, or install via Cargo. Admittedly I don't develop on Windows so testing on that platform so far has not been as extensive as on Linux/Mac (tested on a clean Windows 10 VM).

The precompiled .exe published as a zip [here](https://github.com/Doctave/doctave/releases/latest) _should_ be a "static binary" you can run in a terminal (e.g. Powershell). Do you get an error when you run it in? Could you paste the message here so I could debug the error?

The other option is to install Doctave via Cargo, in which case it is compiled locally on your machine. It looks like you may need the Visual Studio C++ build tools installed to get Rust/Cargo to work. Here's a [blog post](https://reginafurness.medium.com/installing-rust-on-windows-and-visual-studio-code-with-wsl-fa4fb92ffd1) describing how to do that. Rust's own documentation for installing Rust/Cargo on Windows can be found [here](https://forge.rust-lang.org/infra/other-installation-methods.html).

Let me know if either of those options work.
