### ISSUE TITLE
New configuration option: Display the first headline in navigation menu instead of the Filename?

### ISSUE THREAD

**Issue by CleanCodeDeveloper** [Doctave/doctave#42]
First, let me start by saying thank you for this great project. It was very easy to get started. I had my first demo website generated within minutes!

However, there is one think i run into:

Would it be useful to add a configuration option to use the first markdown headline in a file instead of the filename?
![image](https://user-images.githubusercontent.com/16760760/149773765-67f3602b-00a7-4bde-9449-5bf286e51e80.png)

I know that i can achieve the desired outcome by adding
```yaml
---
title: My.Namespace.Test
---
```
on top of this each file.

My use case is the document generation for a few libraries. Unfortunately, i can not change the README.md files because there are used in different places. That's why i would prefer a configuration toggle.

**Comment by CleanCodeDeveloper** [comment]
I created a build script which iterates over all markdown files, reads the first headline and inserts title yaml header into each file. Works very well for me, consider this request as solved.

Btw: doctave is really great! It was a pleasure to use, thank you!

**Comment by begleynk** [comment]
Thanks for the kind words! Glad you found a solution here. I think the proper solution however is described in #32 like you also mentioned. That will be coming in a future release :)
