### ISSUE TITLE
Error after editing the files newly added

### ISSUE THREAD

**Issue by RenukaMane** [Doctave/doctave#43]
I am trying to test Doctave on Windows. Have initiated the website, however after editing some of the files I am getting the following error. Can you tell me how can I resolve this error.
 
![Screenshot 2022-03-11 154008](https://user-images.githubusercontent.com/53396422/157848418-131ec62a-e874-4439-8d31-fdb527a8a281.jpg)

**Comment by RenukaMane** [comment]
Hello. Thanks for your support. Have added a few pages to the site and its working fine. However I tried adding path to the doctave.yaml file for the new pages and faced the same issue again.

Diagrams.md file:
![Diagrams](https://user-images.githubusercontent.com/53396422/158551459-d5be2d90-a44b-4b60-bb79-85ef3bbcef8e.jpg)

doctave.yaml file:
![doctave_yaml](https://user-images.githubusercontent.com/53396422/158551609-5a6fd1f1-87b4-4e14-ba7b-49435a710c3d.jpg)

error:
![error](https://user-images.githubusercontent.com/53396422/158551743-dd607805-66cc-4b1d-a3d9-d85786361dd8.jpg)

**Comment by begleynk** [comment]
That error is pointing to the `doctave.yaml` file not being formatted correctly. Could you try using a tool [like this one](https://codebeautify.org/yaml-validator) to see if it is actually correct? Granted the screenshot you show does seem to be a valid yaml doc.

Note that the `doctave.yaml` file should _not_ have the trailing `---` characters. I was able to reproduce the error you got by adding that trailing line.

The `---` section means "start of a yaml document". If you add another one in this context, the file can't be parsed. this is different from frontematter sections in your `.md` files, where the second `---` character identifies where the frontmatter yaml section ends and the markdown starts.

**Comment by RenukaMane** [comment]
Thank you, the error is resolved.
