### ISSUE TITLE
Distorted Format after building the site

### ISSUE THREAD

**Issue by RenukaMane** [Doctave/doctave#45]
Hello 

I am tried to build a documentation site with the examples.md page as well as a few new pages added to it. However after building the site in release mode the contents of the html pages are distorted also the diagrams drawn with mermaidJS are not visible.
Can you help me out with this issue. 

![Screenshot (21)](https://user-images.githubusercontent.com/53396422/159425335-b33e91e5-15bf-4abd-9744-6e0e6989f3e3.png)

**Comment by begleynk** [comment]
The generated site requires a webserver to be rendered - just opening the `.html` files won't work as the CSS and Javascript won't be loaded.

This is why the tool has the `doctave serve` command. It will start a web server locally for you and you can then view the site in your browser in the address http://localhost:4001.

There's a tutorial here in the tool's docs that walks through the steps: https://cli.doctave.com/tutorial
