### ISSUE TITLE
Page title is not parsed when file contains Windows line endings

### ISSUE THREAD

**Issue by ciwchris** [Doctave/doctave#8]
When generating a new Doctave site on Windows, `doctave init`, the `Examples` page is generated with Windows line endings. These line endings prevent the `title` from being parsed by Doctave and instead are included as markdown content, as if it were just markdown content. The same issue occurs when generating new files on Windows, because they also contain Windows line endings. After changing the files to Unix line endings then the `title` is parsed by Doctave and the page's title is displayed as expected.

![Screenshot 2021-10-12 at 11-54-14 examples](https://user-images.githubusercontent.com/350318/137018045-0b8f70d0-ac2e-4c94-9c8f-2b59afb69865.png)

**Comment by begleynk** [comment]
Thank you Chris for such a detailed bug report! I'm going to dig into this today - my guess is that this should be a reasonably straightforward fix in the frontmatter parser.
